pipeline {
  agent {
    docker {
      image 'myapp:cicd'
    }

  }
  stages {
    stage('Build') {
      agent any
      steps {
        sh 'mvn compile'
      }
    }

    stage('Test') {
      parallel {
        stage('Test Unit') {
          steps {
            sh 'mvn test'
          }
        }

        stage('Test Integration') {
          steps {
            sh 'mvn verify'
          }
        }

      }
    }

    stage('Static Code Analysis') {
      steps {
        sh 'docker run --rm --network ecosystem -v $(pwd):/usr/src sonarsource/sonar-scanner-cli'
      }
    }

    stage('Publish Artifact') {
      steps {
        sh 'docker build . -t localhost:5000/myapp:$(git log -1 --format="%h")'
        sh 'docker push localhost:5000/myapp:$(git log -1 --format="%h")'
        sh 'docker rmi localhost:5000/myapp:$(git log -1 --format="%h")'
      }
    }

  }
}
