pipeline {
    agent any

    options {
        timeout(time: 1, unit: 'HOURS')
        // Prepend all console output generated by the Pipeline run with the time at which the line was emitted
        timestamps()
    }

    stages {
        stage('Example') {
            steps {
                echo 'Hello World'
            }
        }
    }
}